## Numpy
###### NumPy is a Linear Algebra Library in Python and it is the holy grail and the main building block of Data Science using Python.
###### It is bound to several C libraries which makes NumPy one of the fastest libraries in Python.
###### It also has functions for working in domain of linear algebra, fourier transform, and matrices.
###### NumPy is a Python library and is written partially in Python,but most of the parts that require fast computation are written in C or C++.

### Benefits

#### Benefit 1
##### In Python, arrays are a collection of same data types/elements/items (homogeneous) stored in memory Arrays are homogeneous --> similar data types
##### Python list that stores elements of different types (for example, integers, strings, and floats), the list needs to store not only the values but also information about the data type of each element. 
##### This extra information takes up additional memory.
#### Benefit 2
##### faster computation
##### NumPy is a Python library and is written partially in Python,but most of the parts that require fast computation are written in C or C++.
#### Benefit 3
##### Elementwise operation two lists - vectorized operations not possible in Python using lists

In [1]:
#importing library
import numpy as np

In [2]:
#Benefit 1-memory consumption
import sys
list1 = list(range(1,101))
list1

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100]

In [3]:
list1[0]

1

In [4]:
sys.getsizeof(list1[0])

28

In [5]:
sys.getsizeof(list1[0])*len(list1)

2800

In [6]:
import numpy as np
arr=np.arange(1,101)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [7]:
arr[42]

43

In [8]:
arr.itemsize

4

In [9]:
arr.size

100

In [10]:
arr.nbytes

400

In [33]:
#Benfit-2 fast computation
list1=list(range(100))
list2=list(range(100))
for x,y in zip(list1,list2):
    print(x,y)

0 0
1 1
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9
10 10
11 11
12 12
13 13
14 14
15 15
16 16
17 17
18 18
19 19
20 20
21 21
22 22
23 23
24 24
25 25
26 26
27 27
28 28
29 29
30 30
31 31
32 32
33 33
34 34
35 35
36 36
37 37
38 38
39 39
40 40
41 41
42 42
43 43
44 44
45 45
46 46
47 47
48 48
49 49
50 50
51 51
52 52
53 53
54 54
55 55
56 56
57 57
58 58
59 59
60 60
61 61
62 62
63 63
64 64
65 65
66 66
67 67
68 68
69 69
70 70
71 71
72 72
73 73
74 74
75 75
76 76
77 77
78 78
79 79
80 80
81 81
82 82
83 83
84 84
85 85
86 86
87 87
88 88
89 89
90 90
91 91
92 92
93 93
94 94
95 95
96 96
97 97
98 98
99 99


In [12]:
sum1=[x+y for x,y in zip(list1,list2)]
sum1

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198]

In [36]:
start = time.time()
sum1=[x+y for x,y in zip(list1,list2)]
end = time.time()
print("list time: ", end-start)

list time:  0.0010652542114257812


In [47]:
arr1 = np.arange(100)
arr2 = np.arange(100)
print(arr1,arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99] [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [65]:
start = time.time()
arr3 = arr1 + arr2
end = time.time()
print("Numpy time: ", end-start)

Numpy time:  0.000997304916381836


In [39]:
#benefit-3 supports vectorized operation-elemnet wise operation
sum1=[x+y for x,y in zip(list1,list2)]
prod1=[x*y for x,y in zip(list1,list2)]

In [17]:
arr1+arr2

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198])

In [18]:
arr1*arr2

array([   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
        121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
        484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849,
       1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916,
       3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225,
       4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776,
       5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569,
       7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604,
       9801])

In [19]:
#creation of empty array
arr1 = np.array([])   # create an empty array
arr1

array([], dtype=float64)

In [20]:
#np.append(arr, [new_elements])
arr1=np.append(arr1, [1, 2, 3])
arr1#by default creates elements of float type

array([1., 2., 3.])

In [21]:
#np.insert(arr, index, value)
arr1=np.insert(arr1,2,10)
arr1

array([ 1.,  2., 10.,  3.])

In [22]:
arr1=np.insert(arr1,2,[20,15])
arr1

array([ 1.,  2., 20., 15., 10.,  3.])

In [23]:
arr1=np.delete(arr1, 1)
arr1

array([ 1., 20., 15., 10.,  3.])

In [24]:
arr1=np.delete(arr1,[1,4])
arr1

array([ 1., 15., 10.])

In [69]:
arr2 = np.array([], dtype=int)

In [70]:
arr2 = np.append(arr2, [1, 2, 3])
print(arr2)

[1 2 3]


In [68]:
arr2 = np.array([], dtype=int)
arr2 = np.append(arr, [1, 2, 3])
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99  1  2  3]


In [26]:
#try insert and delete

### Creation of 1D array

In [27]:
arr1=np.array([1,2,3,10,20,15])
print(arr1)
print(type(arr1))
arr1

[ 1  2  3 10 20 15]
<class 'numpy.ndarray'>


array([ 1,  2,  3, 10, 20, 15])

#### array inspection
"""
ndim: number of dimensions

shape:returns a tuple with each index having the number of corresponding elements

size: it counts the no. of elements along a given axis, by default it will count total no. of elements in array

dtype: data type of array elements

itemsize: byte size of each array element

nbytes: total size of array and it is equal to itemsize X size
"""

In [28]:
print(arr1)
print(arr1.ndim)
print(arr1.shape)
print(arr1.size)
print(arr1.dtype)
print(arr1.itemsize)
print(arr1.nbytes)#size*itemsize

[ 1  2  3 10 20 15]
1
(6,)
6
int32
4
24


#### Creation of 2D array

In [29]:
arr2=np.array([[23,89,90],[23,92,12],[23,14,90]])#looks like nested lists
print(arr2)#stack of 1D array

[[23 89 90]
 [23 92 12]
 [23 14 90]]


In [30]:
print(arr2.ndim)
print(arr2.shape)#returns row,column
print(arr2.size)
print(arr2.dtype)
print(arr2.itemsize)
print(arr2.nbytes)

2
(3, 3)
9
int32
4
36


#### Creation of 3D array

In [1]:
import numpy as np
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[1,4,3],[4,5,6]]])#stack of 2D arrays
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[ 1  4  3]
  [ 4  5  6]]]


In [32]:
print(arr3.ndim)
print(arr3.shape)#returns layers,rows,columns
print(arr3.size)
print(arr3.dtype)
print(arr3.itemsize)
print(arr3.nbytes)

3
(2, 2, 3)
12
int32
4
48
